create table events
(
    id               bigint auto_increment
        primary key,
    DATE_AND_TIME    datetime     not null,
    DOSE_DESCRIPTION varchar(255) null,
    REASON_TO_CANCEL varchar(255) null,
    STATUS           varchar(255) not null,
    PROC_OR_MED_ID   bigint       not null,
    PATIENT_ID       bigint       not null
)
    engine = MyISAM;

create index FK3usmu4qwjiap3nac4e8viae76
    on events (PATIENT_ID);

create index FK5ob78vbvrf7prnms5ycr62w9b
    on events (PROC_OR_MED_ID);

INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (1, '2021-02-16 07:00:00', null, null, 'DONE', 1, 1);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (2, '2021-02-19 07:00:00', null, 'There was no time', 'CANCELED', 1, 1);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (3, '2021-02-23 07:00:00', null, null, 'DONE', 1, 1);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (4, '2021-02-26 07:00:00', null, null, 'CANCELED', 1, 1);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (5, '2021-03-02 07:00:00', null, null, 'DONE', 1, 1);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (6, '2021-03-05 07:00:00', null, null, 'DONE', 1, 1);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (51, '2021-02-24 14:45:00', null, null, 'DONE', 4, 4);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (44, '2021-02-21 04:45:00', null, null, 'DONE', 4, 4);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (45, '2021-02-21 14:45:00', null, null, 'DONE', 4, 4);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (49, '2021-02-23 14:45:00', null, null, 'PLANNED', 4, 4);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (48, '2021-02-23 04:45:00', null, null, 'PLANNED', 4, 4);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (47, '2021-02-22 14:45:00', null, null, 'PLANNED', 4, 4);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (24, '2021-02-22 07:00:00', null, 'There was no medicine', 'CANCELED', 2, 2);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (25, '2021-02-18 07:00:00', null, 'There was no medicine', 'CANCELED', 2, 2);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (26, '2021-03-01 07:00:00', null, null, 'DONE', 2, 2);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (27, '2021-02-25 07:00:00', null, null, 'DONE', 2, 2);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (50, '2021-02-24 04:45:00', null, null, 'PLANNED', 4, 4);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (46, '2021-02-22 04:45:00', null, null, 'PLANNED', 4, 4);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (52, '2021-02-25 04:45:00', null, null, 'PLANNED', 4, 4);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (53, '2021-02-25 14:45:00', null, null, 'PLANNED', 4, 4);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (54, '2021-02-26 04:45:00', null, null, 'PLANNED', 4, 4);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (55, '2021-02-26 14:45:00', null, null, 'PLANNED', 4, 4);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (56, '2021-02-27 04:45:00', null, null, 'PLANNED', 4, 4);
INSERT INTO newdb.events (id, DATE_AND_TIME, DOSE_DESCRIPTION, REASON_TO_CANCEL, STATUS, PROC_OR_MED_ID, PATIENT_ID) VALUES (57, '2021-02-27 14:45:00', null, null, 'PLANNED', 4, 4);